// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dna2sig
NumericVector dna2sig(SEXP sequence);
RcppExport SEXP sigbin_dna2sig(SEXP sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequence(sequenceSEXP);
    rcpp_result_gen = Rcpp::wrap(dna2sig(sequence));
    return rcpp_result_gen;
END_RCPP
}
