# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sequence_to_signal_cpp <- function(seq) {
    .Call('sigbin_sequence_to_signal_cpp', PACKAGE = 'sigbin', seq)
}

hjorth_params_multi_seq_cpp <- function(seq_set, max_seq_len, offset, activity, mobility, complexity) {
    invisible(.Call('sigbin_hjorth_params_multi_seq_cpp', PACKAGE = 'sigbin', seq_set, max_seq_len, offset, activity, mobility, complexity))
}

hjorth_params_single_sig_cpp <- function(signal, result) {
    invisible(.Call('sigbin_hjorth_params_single_sig_cpp', PACKAGE = 'sigbin', signal, result))
}

hjorth_params_multi_sig_cpp <- function(sig_list, activity, mobility, complexity) {
    invisible(.Call('sigbin_hjorth_params_multi_sig_cpp', PACKAGE = 'sigbin', sig_list, activity, mobility, complexity))
}

