# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert DNA sequence into numeric signal.
#'
#' @param sequence DNAString or DNAStringSet object.
#' @return Numeric vector with signal
#'
#' @examples
#' sig <- dna2sig(DNAString("CCCCCCGGGTGGGTGGGTGGGAAAA"))
#'
dna2sig <- function(sequence) {
    .Call('sigbin_dna2sig', PACKAGE = 'sigbin', sequence)
}

